// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

/**
 Объект, описывающий комментарий из обсуждения в сообществе,

 SeeAlso VK API Reference:
 [CommentBoard](https://vk.com/dev/objects/comment_board
 */
public final class CommentBoard: Codable {
    /// Идентификатор комментария.
    public let id: Int64?
    
    /// Идентификатор автора комментария.
    public let fromId: Int64?
    
    /// Дата создания (в формате Unixtime).
    public let date: UInt64?
    
    /// Текст комментария.
    public let text: String?
    
    /// Медиавложения комментария (фотографии, ссылки и т.п.). Описание массива attachments находится на отдельной странице.
    public let attachments: Attachments?
    
    /// Информация об отметках текущего комментария (если был задан параметр ),
    public final class Likes: Codable {
        
        /// Число пользователей, которым понравился комментарий,
        public let count: Int64?
        
        /// Наличие отметки «Мне нравится» от текущего пользователя (1 — есть, 0 — нет),
        public let userLikes: Int64?
        
        /// Информация о том, может ли текущий пользователь поставить отметку «Мне нравится» (1 — может, 0 — не может).
        public let canLike: Int64?
        
        public init(count: Int64? = nil, userLikes: Int64? = nil, canLike: Int64? = nil) {
            self.count = count
            self.userLikes = userLikes
            self.canLike = canLike
        }
    }
    
    public let likes: Likes?
    
    public init(id: Int64? = nil, fromId: Int64? = nil, date: UInt64? = nil, text: String? = nil, attachments: Attachments? = nil, likes: Likes? = nil) {
        self.id = id
        self.fromId = fromId
        self.date = date
        self.text = text
        self.attachments = attachments
        self.likes = likes
    }

}