// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

/**
 Объект, описывающий товар,

 SeeAlso VK API Reference:
 [MarketItem](https://vk.com/dev/objects/market_item
 */
public struct MarketItem: Codable {
    /// Идентификатор товара.
    public let id: Int64?
    
    /// Идентификатор владельца товара.
    public let ownerId: Int64?
    
    /// Название товара
    public let title: String?
    
    /// Текст описания товара.
    public let description: String?
    
    /// Цена.
    public struct Price: Codable {
        
        /// Цена товара в сотых долях единицы валюты.
        public let amount: String?
        
        /// Валюта. Объект, содержащий поля: 
        public struct Currency: Codable {
            
            /// Идентификатор валюты.
            public let id: Int64?
            
            /// Обозначение валюты.
            public let name: String?
            
            public init(id: Int64? = nil, name: String? = nil) {
                self.id = id
                self.name = name
            }
        }
        
        public let currency: Currency?
        
        public init(amount: String? = nil, currency: Currency? = nil) {
            self.amount = amount
            self.currency = currency
        }
    }
    
    public let price: Price?
    
    /// Габариты товара.
    public struct Dimensions: Codable {
        
        /// Ширина в миллиметрах.
        public let width: Int64?
        
        /// Высота в миллиметрах.
        public let height: Int64?
        
        /// Длина в миллиметрах.
        public let length: Int64?
        
        public init(width: Int64? = nil, height: Int64? = nil, length: Int64? = nil) {
            self.width = width
            self.height = height
            self.length = length
        }
    }
    
    public let dimensions: Dimensions?
    
    /// Вес в граммах.
    public let weight: Int64?
    
    /// Категория товара.
    public struct Category: Codable {
        
        /// Идентификатор категории.
        public let id: Int64?
        
        /// Название категории.
        public let name: String?
        
        /// Секция. Объект, содержащий поля: 
        public struct Section: Codable {
            
            /// Идентификатор секции.
            public let id: Int64?
            
            /// Название секции.
            public let name: String?
            
            public init(id: Int64? = nil, name: String? = nil) {
                self.id = id
                self.name = name
            }
        }
        
        public let section: Section?
        
        public init(id: Int64? = nil, name: String? = nil, section: Section? = nil) {
            self.id = id
            self.name = name
            self.section = section
        }
    }
    
    public let category: Category?
    
    /// URL изображения-обложки товара.
    public let thumbPhoto: String?
    
    /// Дата создания товара в формате Unixtime.
    public let date: UInt64?
    
    /// Статус доступности товара.
    public enum Availability: Int64, Codable {
        /// 0 — товар доступен;
        case tovar_dostupen = 0
    
        /// 2 — товар недоступен.
        case tovar_nedostupen = 2
    
        /// 1 — товар удален;
        case tovar_udalen = 1
    }
    
    public let availability: Availability?
    
    /// True, если объект добавлен в закладки у текущего пользователя.
    public struct IsFavorite: Codable {
        
        
        public init() {
        }
    }
    
    public let isFavorite: IsFavorite?
    
    /// Артикул товара,
    public let sku: String?
    
    /// При получении объектов, прямого доступа к которым может не быть, например, фотографий или видео в новостях, вместе с объектами приходит поле access_key, которое необходимо передавать при получении этих объектов напрямую или при совершении с ними действий. 
    public let accessKey: String?
    
    public init(id: Int64? = nil, ownerId: Int64? = nil, title: String? = nil, description: String? = nil, price: Price? = nil, dimensions: Dimensions? = nil, weight: Int64? = nil, category: Category? = nil, thumbPhoto: String? = nil, date: UInt64? = nil, availability: Availability? = nil, isFavorite: IsFavorite? = nil, sku: String? = nil, accessKey: String? = nil) {
        self.id = id
        self.ownerId = ownerId
        self.title = title
        self.description = description
        self.price = price
        self.dimensions = dimensions
        self.weight = weight
        self.category = category
        self.thumbPhoto = thumbPhoto
        self.date = date
        self.availability = availability
        self.isFavorite = isFavorite
        self.sku = sku
        self.accessKey = accessKey
    }

}