// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

/**
 Объект, содержащий информацию о заказе.

 SeeAlso VK API Reference:
 [MarketOrder](https://vk.com/dev/objects/market_order
 */
public final class MarketOrder: Codable {
    /// Идентификатор заказа.
    public let id: Int64?
    
    /// Идентификатор сообщества.
    public let groupId: UInt64?
    
    /// Идентификатор покупателя.
    public let userId: Int64?
    
    /// Дата создания заказа в формате Unixtime.
    public let date: UInt64?
    
    /// Идентификатор группы вариантов.
    public let variantsGroupingId: Int64?
    
    /// Является ли вариант основным.
    public let isMainVariant: Bool?
    
    /// Массив объектов,
    public final class PropertyValues: Codable {
        
        /// Идентификатор варианта.
        public let variantId: Int64?
        
        /// Название варианта.
        public let variantName: String?
        
        /// Название свойства.
        public let propertyName: String?
        
        public init(variantId: Int64? = nil, variantName: String? = nil, propertyName: String? = nil) {
            self.variantId = variantId
            self.variantName = variantName
            self.propertyName = propertyName
        }
    }
    
    public let propertyValues: [PropertyValues]?
    
    /// Количество товара в корзине.
    public let cartQuantity: Int64?
    
    /// Статус заказа:
    public let status: Int64?
    
    /// Количество товаров в заказе.
    public let itemsCount: Int64?
    
    /// Общая стоимость заказа.
    public final class TotalPrice: Codable {
        
        /// Стоимость в сотых долях единицы валюты.
        public let amount: String?
        
        /// Валюта. Объект, содержащий поля: 
        public final class Currency: Codable {
            
            /// Идентификатор валюты.
            public let id: Int64?
            
            /// Обозначение валюты.
            public let name: String?
            
            public init(id: Int64? = nil, name: String? = nil) {
                self.id = id
                self.name = name
            }
        }
        
        public let currency: Currency?
        
        /// Строковое представление стоимости заказа.
        public let text: String?
        
        public init(amount: String? = nil, currency: Currency? = nil, text: String? = nil) {
            self.amount = amount
            self.currency = currency
            self.text = text
        }
    }
    
    public let totalPrice: TotalPrice?
    
    /// Номер заказа, состоящий из идентификатора покупателя и идентификатора заказа.
    public let displayOrderId: String?
    
    /// Комментарий к заказу.
    public let comment: String?
    
    /// Массив объектов, описывающих товары. Возвращается не больше 5 случайных товаров заказа.
    public final class PreviewOrderItems: Codable {
        
        
        public init() {
        }
    }
    
    public let previewOrderItems: [PreviewOrderItems]?
    
    /// Информация о доставке.
    public final class Delivery: Codable {
        
        /// Адрес доставки.
        public let address: String?
        
        /// Тип доставки.
        public let `type`: String?
        
        /// Трек-номер для отслеживания заказа.
        public let trackNumber: String?
        
        /// Ссылка для отслеживания заказа по трек-номеру.
        public let trackLink: String?
        
        /// Информация о пункте выдачи.
        public final class DeliveryPoint: Codable {
            
            
            public init() {
            }
        }
        
        public let deliveryPoint: DeliveryPoint?
        
        public init(address: String? = nil, type: String? = nil, trackNumber: String? = nil, trackLink: String? = nil, deliveryPoint: DeliveryPoint? = nil) {
            self.address = address
            self.type = `type`
            self.trackNumber = trackNumber
            self.trackLink = trackLink
            self.deliveryPoint = deliveryPoint
        }
    }
    
    public let delivery: Delivery?
    
    /// Информация о покупателе.
    public final class Recipient: Codable {
        
        /// Имя покупателя.
        public let name: String?
        
        /// Номер покупателя.
        public let phone: String?
        
        /// Строковое представление информации о покупателе.
        public let displayText: String?
        
        public init(name: String? = nil, phone: String? = nil, displayText: String? = nil) {
            self.name = name
            self.phone = phone
            self.displayText = displayText
        }
    }
    
    public let recipient: Recipient?
    
    public init(id: Int64? = nil, groupId: UInt64? = nil, userId: Int64? = nil, date: UInt64? = nil, variantsGroupingId: Int64? = nil, isMainVariant: Bool? = nil, propertyValues: [PropertyValues]? = nil, cartQuantity: Int64? = nil, status: Int64? = nil, itemsCount: Int64? = nil, totalPrice: TotalPrice? = nil, displayOrderId: String? = nil, comment: String? = nil, previewOrderItems: [PreviewOrderItems]? = nil, delivery: Delivery? = nil, recipient: Recipient? = nil) {
        self.id = id
        self.groupId = groupId
        self.userId = userId
        self.date = date
        self.variantsGroupingId = variantsGroupingId
        self.isMainVariant = isMainVariant
        self.propertyValues = propertyValues
        self.cartQuantity = cartQuantity
        self.status = status
        self.itemsCount = itemsCount
        self.totalPrice = totalPrice
        self.displayOrderId = displayOrderId
        self.comment = comment
        self.previewOrderItems = previewOrderItems
        self.delivery = delivery
        self.recipient = recipient
    }

}