// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

/**
 Объект, описывающий подборку товаров,

 SeeAlso VK API Reference:
 [MarketAlbum](https://vk.com/dev/objects/market_album
 */
public final class MarketAlbum: Codable {
    /// Идентификатор подборки.
    public let id: Int64?
    
    /// Идентификатор владельца подборки.
    public let ownerId: Int64?
    
    /// Название подборки.
    public let title: String?
    
    /// Обложка подборки, объект, описывающий фотографию.
    public final class Photo: Codable {
        
        
        public init() {
        }
    }
    
    public let photo: Photo?
    
    /// Число товаров в подборке.
    public let count: Int64?
    
    /// Дата обновления подборки в формате Unixtime.
    public let updatedTime: UInt64?
    
    /// При получении объектов, прямого доступа к которым может не быть, например, фотографий или видео в новостях, вместе с объектами приходит поле access_key, которое необходимо передавать при получении этих объектов напрямую или при совершении с ними действий. 
    public let accessKey: String?
    
    public init(id: Int64? = nil, ownerId: Int64? = nil, title: String? = nil, photo: Photo? = nil, count: Int64? = nil, updatedTime: UInt64? = nil, accessKey: String? = nil) {
        self.id = id
        self.ownerId = ownerId
        self.title = title
        self.photo = photo
        self.count = count
        self.updatedTime = updatedTime
        self.accessKey = accessKey
    }

}