// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

/**
 Список объектов › Личное сообщение Для версии API с 5.80 Для версий API ниже 5.80

 SeeAlso VK API Reference:
 [Message](https://vk.com/dev/objects/message
 */
public struct Message: Codable {
    /// Идентификатор сообщения.
    public let id: Int64?
    
    /// Время отправки в Unixtime.
    public let date: UInt64?
    
    /// Идентификатор назначения.
    public var peerId: Int64?
    
    /// Идентификатор отправителя.
    public let fromId: Int64?
    
    /// Текст сообщения.
    public let text: String?
    
    /// Идентификатор, используемый при отправке сообщения. Возвращается только для исходящих сообщений.
    public let randomId: Int64?
    
    /// Произвольный параметр для работы с источниками переходов.
    public let ref: String?
    
    /// Произвольный параметр для работы с источниками переходов.
    public let refSource: String?
    
    /// Медиавложения сообщения (фотографии, ссылки и т.п.). Описание массива attachments находится на отдельной странице.
    public let attachments: ArrayByComma<Attachment>?
    
    /// True, если сообщение помечено как важное.
    public let important: Bool?
    
    /// Информация о местоположении ,
    public struct Geo: Codable {
        
        /// Тип места.
        public let `type`: String?
        
        /// Координаты места, Объект, который содержит поля: 
        public struct Coordinates: Codable {
            
            /// Географическая широта.
            public let latitude: Double?
            
            /// Географическая долгота.
            public let longitude: Double?
            
            public init(latitude: Double? = nil, longitude: Double? = nil) {
                self.latitude = latitude
                self.longitude = longitude
            }
        }
        
        public let coordinates: [Coordinates]?
        
        /// Описание места (если оно добавлено), объект с полями: 
        public struct Place: Codable {
            
            /// Идентификатор места (если назначено).
            public let id: Int64?
            
            /// Название места (если назначено).
            public let title: String?
            
            /// Географическая широта.
            public let latitude: Int64?
            
            /// Географическая долгота.
            public let longitude: Int64?
            
            /// Дата создания (если назначено).
            public let created: String?
            
            /// URL изображения-иконки.
            public let icon: String?
            
            /// Название страны.
            public let country: String?
            
            /// Название города.
            public let city: String?
            
            public init(id: Int64? = nil, title: String? = nil, latitude: Int64? = nil, longitude: Int64? = nil, created: String? = nil, icon: String? = nil, country: String? = nil, city: String? = nil) {
                self.id = id
                self.title = title
                self.latitude = latitude
                self.longitude = longitude
                self.created = created
                self.icon = icon
                self.country = country
                self.city = city
            }
        }
        
        public let place: Place?
        
        /// Информация о том, отображается ли карта.
        public let showmap: Int64?
        
        public init(type: String? = nil, coordinates: [Coordinates]? = nil, place: Place? = nil, showmap: Int64? = nil) {
            self.type = `type`
            self.coordinates = coordinates
            self.place = place
            self.showmap = showmap
        }
    }
    
    public let geo: Geo?
    
    /// Сервисное поле для сообщений ботам (полезная нагрузка).
    public let payload: Message.Payload?
    
    /// Объект клавиатуры для ботов.
    public let keyboard: Keyboard?
    
    /// Массив пересланных сообщений (если есть). Максимальное количество элементов — 100. Максимальная глубина вложенности для пересланных сообщений — 45, общее максимальное количество в цепочке с учетом вложенности — 500.
    public let fwdMessages: [Message]?
    
    /// Сообщение, в ответ на которое отправлено текущее.
    public let replyMessage: [Message]?
    
    /// Информация о сервисном действии с чатом.
    public struct Action: Codable {
        
        /// Тип действия. Возможные значения: 
        public enum `Type`: String, Codable {
            /// chat_kick_user — исключен пользователь;
            case chat_kick_user
        
            /// chat_photo_update — обновлена фотография беседы;
            case chat_photo_update
        
            /// chat_title_update — обновлено название беседы;
            case chat_title_update
        
            /// chat_unpin_message — откреплено сообщение;
            case chat_unpin_message
        
            /// chat_invite_user_by_link — пользователь присоединился к беседе по ссылке.
            case chat_invite_user_by_link
        
            /// chat_invite_user — приглашен пользователь;
            case chat_invite_user
        
            /// chat_create — создана беседа;
            case chat_create
        
            /// chat_photo_remove — удалена фотография беседы;
            case chat_photo_remove
        
            /// chat_pin_message — закреплено сообщение;
            case chat_pin_message
        }
        
        public let `type`: Type?
        
        /// Идентификатор пользователя (если > 0) или email (если < 0), которого пригласили или исключили (для служебных сообщений с type = chat_invite_user или chat_kick_user). Идентификатор пользователя, который закрепил/открепил сообщение для action = chat_pin_message или chat_unpin_message.
        public let memberId: Int64?
        
        /// Название беседы (для служебных сообщений с type = chat_create или chat_title_update).
        public let text: String?
        
        /// Email, который пригласили или исключили (для служебных сообщений с type = chat_invite_user или chat_kick_user и отрицательным member_id).
        public let email: String?
        
        /// Изображение-обложка чата. Объект, который содержит поля: 
        public struct Photo: Codable {
            
            /// URL изображения 50x50px.
            public let photo50: String?
            
            /// URL изображения 100x100px.
            public let photo100: String?
            
            /// URL изображения 200x200px.
            public let photo200: String?
            
            public init(photo50: String? = nil, photo100: String? = nil, photo200: String? = nil) {
                self.photo50 = photo50
                self.photo100 = photo100
                self.photo200 = photo200
            }
        }
        
        public let photo: Photo?
        
        public init(type: Type? = nil, memberId: Int64? = nil, text: String? = nil, email: String? = nil, photo: Photo? = nil) {
            self.type = `type`
            self.memberId = memberId
            self.text = text
            self.email = email
            self.photo = photo
        }
    }
    
    public let action: Action?
    
    /// Только для сообщений сообщества. Содержит идентификатор пользователя (администратора сообщества), отправившего это сообщение.
    public let adminAuthorId: Int64?
    
    /// Уникальный автоматически увеличивающийся номер для всех сообщений с этим peer.
    public let conversationMessageId: Int64?
    
    /// Это сообщение обрезано для бота.
    public let isCropped: Bool?
    
    /// Количество участников.
    public let membersCount: Int64?
    
    /// Дата, когда сообщение было обновлено в Unixtime.
    public let updateTime: UInt64?
    
    /// Было ли вложенное аудиосообщение уже прослушано вами.
    public let wasListened: Bool?
    
    /// Дата, когда сообщение было закреплено в Unixtime.
    public let pinnedAt: UInt64?
    
    /// Строка для сопоставления пользователя Notify и ВКонтакте. Данные копирует в момент ответа пользователем на сообщение из Notify, отправленное с параметром session_id. Подробнее про Notify: https://notify.mail.
    public let messageTag: String?
    
    public init(id: Int64? = nil, date: UInt64? = nil, peerId: Int64? = nil, fromId: Int64? = nil, text: String? = nil, randomId: Int64? = nil, ref: String? = nil, refSource: String? = nil, attachments: ArrayByComma<Attachment>? = nil, important: Bool? = nil, geo: Geo? = nil, payload: Message.Payload? = nil, keyboard: Keyboard? = nil, fwdMessages: [Message]? = nil, replyMessage: [Message]? = nil, action: Action? = nil, adminAuthorId: Int64? = nil, conversationMessageId: Int64? = nil, isCropped: Bool? = nil, membersCount: Int64? = nil, updateTime: UInt64? = nil, wasListened: Bool? = nil, pinnedAt: UInt64? = nil, messageTag: String? = nil) {
        self.id = id
        self.date = date
        self.peerId = peerId
        self.fromId = fromId
        self.text = text
        self.randomId = randomId
        self.ref = ref
        self.refSource = refSource
        self.attachments = attachments
        self.important = important
        self.geo = geo
        self.payload = payload
        self.keyboard = keyboard
        self.fwdMessages = fwdMessages
        self.replyMessage = replyMessage
        self.action = action
        self.adminAuthorId = adminAuthorId
        self.conversationMessageId = conversationMessageId
        self.isCropped = isCropped
        self.membersCount = membersCount
        self.updateTime = updateTime
        self.wasListened = wasListened
        self.pinnedAt = pinnedAt
        self.messageTag = messageTag
    }

}