// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

/**
 Объект описывает беседу с пользователем, сообществом или групповой чат.

 SeeAlso VK API Reference:
 [Conversation](https://vk.com/dev/objects/conversation
 */
public final class Conversation: Codable {
    /// Информация о собеседнике.
    public final class Peer: Codable {
        
        /// Идентификатор назначения.
        public let id: Int64?
        
        /// Тип. Возможные значения: user, chat, group, email
        public enum `Type`: String, Codable {
            case user
            case chat
            case group
            case email
        }
        
        let `type`: Type?
        
        /// Локальный идентификатор назначения. Для чатов — id - 2000000000, для сообществ — -id, для e-mail — -(id+2000000000).
        public let localId: Int64?
        
        public init(id: Int64? = nil, type: Type? = nil, localId: Int64? = nil) {
            self.id = id
            self.type = `type`
            self.localId = localId
        }
    }
    
    let peer: Peer?
    
    /// Идентификатор последнего прочтенного входящего сообщения.
    public let inRead: Int64?
    
    /// Идентификатор последнего прочтенного исходящего сообщения.
    public let outRead: Int64?
    
    /// Число непрочитанных сообщений.
    public let unreadCount: Int64?
    
    /// , если диалог помечен как важный (только для сообщений сообществ).
    public let important: Bool?
    
    /// , если диалог помечен как неотвеченный (только для сообщений сообществ).
    public let unanswered: Bool?
    
    /// Настройки Push-уведомлений.
    public final class PushSettings: Codable {
        
        /// Timestamp, до которого оповещения отключены.
        public let disabledUntil: Int64?
        
        /// Передается в случае, если оповещения отключены навсегда, содержит true.
        public let disabledForever: Bool?
        
        /// Передается в случае, если отключен звук оповещений, содержит true.
        public let noSound: Bool?
        
        public init(disabledUntil: Int64? = nil, disabledForever: Bool? = nil, noSound: Bool? = nil) {
            self.disabledUntil = disabledUntil
            self.disabledForever = disabledForever
            self.noSound = noSound
        }
    }
    
    let pushSettings: PushSettings?
    
    /// Информация о том, может ли пользователь писать в диалог.
    public final class CanWrite: Codable {
        
        /// True, если пользователь может писать в диалог.
        public let allowed: Bool?
        
        /// Код ошибки для allowed = false. Возможные значения: 18 — пользователь заблокирован или удален. 900 — нельзя отправить сообщение пользователю, который в чёрном списке. 901 — пользователь запретил сообщения от сообщества. 902 — пользователь запретил присылать ему сообщения с помощью настроек приватности. 915 — в сообществе отключены сообщения. 916 — в сообществе заблокированы сообщения. 917 — нет доступа к чату. 918 — нет доступа к e-mail. 203 — нет доступа к сообществу.
        public enum Reason: Int64, Codable {
            case net_dostupa_k_catu = 917
            case net_dostupa_k_email = 918
            case v_soobsestve_otkluceny_soobsenia = 915
            case polzovatel_zapretil_soobsenia_ot_soobsestva = 901
            case v_soobsestve_zablokirovany_soobsenia = 916
            case net_dostupa_k_soobsestvu = 203
            case polzovatel_zapretil_prisylat_emu_soobsenia_s_pomosu_nastroek_privatnosti = 902
            case nelza_otpravit_soobsenie_polzovatelu_kotoryj_v_cernom_spiske = 900
            case polzovatel_zablokirovan_ili_udalen = 18
        }
        
        let reason: Reason?
        
        public init(allowed: Bool? = nil, reason: Reason? = nil) {
            self.allowed = allowed
            self.reason = reason
        }
    }
    
    let canWrite: CanWrite?
    
    /// Настройки чата.
    public final class ChatSettings: Codable {
        
        /// Число участников.
        public let membersCount: Int64?
        
        /// Название.
        public let title: String?
        
        /// Объект закреплённого сообщения, если есть.
        public final class PinnedMessage: Codable {
            
            
            public init() {
            }
        }
        
        let pinnedMessage: PinnedMessage?
        
        /// (string) — статус текущего пользователя. Возможные значения: in — состоит в чате. kicked — исключён из чата. left — покинул чат.
        public enum State: String, Codable {
            case isklucen_iz_cata = "kicked"
            case sostoit_v_cate = "in"
            case pokinul_cat = "left"
        }
        
        let state: State?
        
        /// Изображение-обложка чата. Объект, который содержит поля: photo_50 (string) — URL изображения 50x50px. photo_100 (string) — URL изображения 100x100px. photo_200 (string) — URL изображения 200x200px.
        public final class Photo: Codable {
            
            /// URL изображения 50x50px.
            public let photo50: String?
            
            /// URL изображения 100x100px.
            public let photo100: String?
            
            /// URL изображения 200x200px.
            public let photo200: String?
            
            public init(photo50: String? = nil, photo100: String? = nil, photo200: String? = nil) {
                self.photo50 = photo50
                self.photo100 = photo100
                self.photo200 = photo200
            }
        }
        
        let photo: Photo?
        
        /// Идентификаторы последних пользователей, писавших в чат.
        public let activeIds: [Int64]?
        
        /// Информация о том, является ли беседа каналом сообщества.
        public let isGroupChannel: Bool?
        
        public init(membersCount: Int64? = nil, title: String? = nil, pinnedMessage: PinnedMessage? = nil, state: State? = nil, photo: Photo? = nil, activeIds: [Int64]? = nil, isGroupChannel: Bool? = nil) {
            self.membersCount = membersCount
            self.title = title
            self.pinnedMessage = pinnedMessage
            self.state = state
            self.photo = photo
            self.activeIds = activeIds
            self.isGroupChannel = isGroupChannel
        }
    }
    
    let chatSettings: ChatSettings?
    
    public init(peer: Peer? = nil, inRead: Int64? = nil, outRead: Int64? = nil, unreadCount: Int64? = nil, important: Bool? = nil, unanswered: Bool? = nil, pushSettings: PushSettings? = nil, canWrite: CanWrite? = nil, chatSettings: ChatSettings? = nil) {
        self.peer = peer
        self.inRead = inRead
        self.outRead = outRead
        self.unreadCount = unreadCount
        self.important = important
        self.unanswered = unanswered
        self.pushSettings = pushSettings
        self.canWrite = canWrite
        self.chatSettings = chatSettings
    }

}