// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

/**
 Список объектов › Прикрепленная ссылка Объект, описывающий прикрепленную ссылку в сообщении, комментарии или записи на стене, содержит следующие поля: url string URL ссылки. title string заголовок ссылки. caption string подпись ссылки (если имеется). description string описание ссылки. photo object изображение превью, объект фотографии (если имеется). product object информация о продукте (если имеется). Поле возвращается для ссылок на магазины, например, Aliexpress. Объект с единственным полем price (object), которое описано на отдельной странице. button object информация о кнопке для перехода (если имеется). Объект описан на отдельной странице. preview_page string идентификатор вики-страницы с контентом для предпросмотра содержимого страницы. Возвращается в формате "owner_id_page_id". preview_url string URL страницы с контентом для предпросмотра содержимого страницы.

 SeeAlso VK API Reference:
 [Link](https://vk.com/dev/objects/link
 */
public final class Link: Codable {
    /// URL ссылки.
    public let url: String?
    
    /// Заголовок ссылки.
    public let title: String?
    
    /// Подпись ссылки (если имеется).
    public let caption: String?
    
    /// Описание ссылки.
    public let description: String?
    
    /// Изображение превью, объект фотографии (если имеется).
    public final class Photo: Codable {
        
        
        public init() {
        }
    }
    
    public let photo: Photo?
    
    /// Информация о продукте (если имеется). Поле возвращается для ссылок на магазины, например, Aliexpress. Объект с единственным полем price (object), которое описано на отдельной странице.
    public final class Product: Codable {
        
        
        public init() {
        }
    }
    
    public let product: Product?
    
    /// Информация о кнопке для перехода (если имеется). Объект описан на отдельной странице.
    public final class Button: Codable {
        
        
        public init() {
        }
    }
    
    public let button: Button?
    
    /// Идентификатор вики-страницы с контентом для предпросмотра содержимого страницы. Возвращается в формате "owner_id_page_id".
    public let previewPage: String?
    
    /// URL страницы с контентом для предпросмотра содержимого страницы.
    public let previewUrl: String?
    
    public init(url: String? = nil, title: String? = nil, caption: String? = nil, description: String? = nil, photo: Photo? = nil, product: Product? = nil, button: Button? = nil, previewPage: String? = nil, previewUrl: String? = nil) {
        self.url = url
        self.title = title
        self.caption = caption
        self.description = description
        self.photo = photo
        self.product = product
        self.button = button
        self.previewPage = previewPage
        self.previewUrl = previewUrl
    }

}