// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

/**
 Список объектов › Формат описания размеров фотографии При использовании параметра photo_sizes = 1 в методах для работы с фотографиями, в ответе возвращается информация о копиях исходного изображения разных размеров, представленная в виде массива sizes, содержащего объекты со следующими полями: src string URL копии изображения. width integer ширина копии в пикселах. height integer высота копии в пикселах. type string обозначение размера и пропорций копии.

 SeeAlso VK API Reference:
 [PhotoSizes](https://vk.com/dev/objects/photo_sizes
 */
public final class PhotoSizes: Codable {
    /// URL копии изображения.
    public let src: String?
    
    /// Ширина копии в пикселах.
    public let width: Int64?
    
    /// Высота копии в пикселах.
    public let height: Int64?
    
    /// Обозначение размера и пропорций копии.
    public let `type`: String?
    
    public init(src: String? = nil, width: Int64? = nil, height: Int64? = nil, type: String? = nil) {
        self.src = src
        self.width = width
        self.height = height
        self.type = `type`
    }

}