// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

/**
 Объект , описывающий способ размещения ,

 SeeAlso VK API Reference:
 [PostSource](https://vk.com/dev/objects/post_source
 */
public final class PostSource: Codable {
    /// Тип источника.
    public enum `Type`: String, Codable {
        case rss
        case vk
        case api
        case widget
        case sms
    }
    
    public let `type`: Type?
    
    /// Название платформы, если оно доступно.
    public enum Platform: String, Codable {
        case android
        case iphone
        case wphone
    }
    
    public let platform: Platform?
    
    /// Тип действия (только для = или ).
    public enum Data: String, Codable {
        case poll
        case profile_photo
        case profile_activity
        case comments
        case like
    }
    
    public let data: Data?
    
    /// URL ресурса, с которого была опубликована запись.
    public let url: String?
    
    public init(type: Type? = nil, platform: Platform? = nil, data: Data? = nil, url: String? = nil) {
        self.type = `type`
        self.platform = platform
        self.data = data
        self.url = url
    }

}