// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

/**
 Объект, описывающий стикер, содержит следующие поля(с версии 5.

 SeeAlso VK API Reference:
 [Sticker](https://vk.com/dev/objects/sticker
 */
public final class Sticker: Codable {
    /// Идентификатор набора.
    public let productId: Int64?
    
    /// Идентификатор стикера.
    public let stickerId: Int64?
    
    /// Изображения для стикера (с прозрачным фоном).
    public final class Images: Codable {
        
        /// URL копии изображения.
        public let url: String?
        
        /// Ширина копии в px.
        public let width: Int64?
        
        /// Высота копии в px.
        public let height: Int64?
        
        public init(url: String? = nil, width: Int64? = nil, height: Int64? = nil) {
            self.url = url
            self.width = width
            self.height = height
        }
    }
    
    public let images: [Images]?
    
    /// Изображения для стикера (с непрозрачным фоном).
    public final class ImagesWithBackground: Codable {
        
        /// URL копии изображения.
        public let url: String?
        
        /// Ширина копии в px.
        public let width: Int64?
        
        /// Высота копии в px.
        public let height: Int64?
        
        public init(url: String? = nil, width: Int64? = nil, height: Int64? = nil) {
            self.url = url
            self.width = width
            self.height = height
        }
    }
    
    public let imagesWithBackground: [ImagesWithBackground]?
    
    /// URL анимации стикера.
    public let animationUrl: String?
    
    /// Информация о том, доступен ли стикер.
    public let isAllowed: Bool?
    
    public init(productId: Int64? = nil, stickerId: Int64? = nil, images: [Images]? = nil, imagesWithBackground: [ImagesWithBackground]? = nil, animationUrl: String? = nil, isAllowed: Bool? = nil) {
        self.productId = productId
        self.stickerId = stickerId
        self.images = images
        self.imagesWithBackground = imagesWithBackground
        self.animationUrl = animationUrl
        self.isAllowed = isAllowed
    }

}