// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

/**
 Список объектов › Пользователь 1. Базовые поля 2. Опциональные поля A-L 3. Опциональные поля M-W Объект содержит информацию о пользователе ВКонтакте. Набор полей может меняться в зависимости от вызванного метода и переданных в нем параметров. Обратите внимание — все поля использующие информацию о текущем пользователе (например, blacklisted_by_me) требуют передачи ключа доступа пользователя в запросе, даже если сам метод можно вызывать без ключа доступа.

 SeeAlso VK API Reference:
 [User](https://vk.com/dev/objects/user
 */
public final class User: Codable {
    /// Идентификатор пользователя.
    public let id: Int64
    
    /// Имя.
    public let firstName: String
    
    /// Фамилия.
    public let lastName: String
    
    /// Поле возвращается, если страница пользователя удалена или заблокирована, содержит значение или . В этом случае опциональные поля не возвращаются.
    public let deactivated: String
    
    /// Скрыт ли профиль пользователя настройками приватности.
    public let isClosed: Bool
    
    /// Может ли текущий пользователь видеть профиль при = (например, он есть в друзьях).
    public let canAccessClosed: Bool
    
    /// Содержимое поля «О себе» из профиля.
    public let about: String?
    
    /// Содержимое поля «Деятельность» из профиля.
    public let activities: String?
    
    /// Дата рождения. Возвращается в формате или (если год рождения скрыт). Если дата рождения скрыта целиком, поле отсутствует в ответе.
    public let bdate: String?
    
    /// Информация о том, находится ли текущий пользователь в черном списке.
    public let blacklisted: VkFlag?
    
    /// Информация о том, находится ли пользователь в черном списке у текущего пользователя.
    public let blacklistedByMe: VkFlag?
    
    /// Содержимое поля «Любимые книги» из профиля пользователя.
    public let books: String?
    
    /// Информация о том, может ли текущий пользователь оставлять записи на стене.
    public let canPost: VkFlag?
    
    /// Информация о том, может ли текущий пользователь видеть чужие записи на стене.
    public let canSeeAllPosts: VkFlag?
    
    /// Информация о том, может ли текущий пользователь видеть аудиозаписи.
    public let canSeeAudio: VkFlag?
    
    /// Информация о том, будет ли отправлено уведомление пользователю о заявке в друзья от текущего пользователя.
    public let canSendFriendRequest: VkFlag?
    
    /// Информация о том, может ли текущий пользователь отправить личное сообщение.
    public let canWritePrivateMessage: VkFlag?
    
    /// Информация о карьере пользователя.
    public final class Career: Codable {
        
        /// Идентификатор сообщества (если доступно, иначе company).
        public let groupId: UInt64?
        
        /// Название компании (если доступно, иначе group_id).
        public let company: String?
        
        /// Идентификатор страны.
        public let countryId: Int64?
        
        /// Идентификатор города (если доступно, иначе city_name).
        public let cityId: Int64?
        
        /// Название города (если доступно, иначе city_id).
        public let cityName: String?
        
        /// Год начала работы.
        public let from: Int64?
        
        /// Год окончания работы.
        public let until: Int64?
        
        /// Должность.
        public let position: String?
        
        public init(groupId: UInt64? = nil, company: String? = nil, countryId: Int64? = nil, cityId: Int64? = nil, cityName: String? = nil, from: Int64? = nil, until: Int64? = nil, position: String? = nil) {
            self.groupId = groupId
            self.company = company
            self.countryId = countryId
            self.cityId = cityId
            self.cityName = cityName
            self.from = from
            self.until = until
            self.position = position
        }
    }
    
    public let career: Career?
    
    /// Информация о городе, указанном на странице пользователя в разделе «Контакты».
    public final class City: Codable {
        
        /// Идентификатор города, который можно использовать для получения его названия с помощью метода database.getCitiesById.
        public let id: Int64?
        
        /// Название города.
        public let title: String?
        
        public init(id: Int64? = nil, title: String? = nil) {
            self.id = id
            self.title = title
        }
    }
    
    public let city: City?
    
    /// Количество общих друзей с текущим пользователем.
    public let commonCount: Int64?
    
    /// Возвращает данные об указанных в профиле сервисах пользователя, таких как: skype, facebook, twitter, livejournal, instagram. Для каждого сервиса возвращается отдельное поле с типом , содержащее никнейм пользователя. Например, .
    public let connections: [String: String]?
    
    /// Информация о телефонных номерах пользователя.
    public final class Contacts: Codable {
        
        /// Номер мобильного телефона пользователя (только для Standalone-приложений).
        public let mobilePhone: String?
        
        /// Дополнительный номер телефона пользователя.
        public let homePhone: String?
        
        public init(mobilePhone: String? = nil, homePhone: String? = nil) {
            self.mobilePhone = mobilePhone
            self.homePhone = homePhone
        }
    }
    
    public let contacts: Contacts?
    
    /// Количество различных объектов у пользователя. Поле возвращается только в методе при запросе информации об одном пользователе, с передачей пользовательского .
    public final class Counters: Codable {
        
        /// Количество фотоальбомов.
        public let albums: Int64?
        
        /// Количество видеозаписей.
        public let videos: Int64?
        
        /// Количество аудиозаписей.
        public let audios: Int64?
        
        /// Количество фотографий.
        public let photos: Int64?
        
        /// Количество заметок.
        public let notes: Int64?
        
        /// Количество друзей.
        public let friends: Int64?
        
        /// Количество сообществ.
        public let groups: Int64?
        
        /// Количество друзей онлайн.
        public let onlineFriends: Int64?
        
        /// Количество общих друзей.
        public let mutualFriends: Int64?
        
        /// Количество видеозаписей с пользователем.
        public let userVideos: Int64?
        
        /// Количество подписчиков.
        public let followers: Int64?
        
        /// Количество объектов в блоке «Интересные страницы».
        public final class Pages: Codable {
            
            
            public init() {
            }
        }
        
        public let pages: Pages?
        
        public init(albums: Int64? = nil, videos: Int64? = nil, audios: Int64? = nil, photos: Int64? = nil, notes: Int64? = nil, friends: Int64? = nil, groups: Int64? = nil, onlineFriends: Int64? = nil, mutualFriends: Int64? = nil, userVideos: Int64? = nil, followers: Int64? = nil, pages: Pages? = nil) {
            self.albums = albums
            self.videos = videos
            self.audios = audios
            self.photos = photos
            self.notes = notes
            self.friends = friends
            self.groups = groups
            self.onlineFriends = onlineFriends
            self.mutualFriends = mutualFriends
            self.userVideos = userVideos
            self.followers = followers
            self.pages = pages
        }
    }
    
    public let counters: Counters?
    
    /// Информация о стране, указанной на странице пользователя в разделе «Контакты».
    public final class Country: Codable {
        
        /// Идентификатор страны, который можно использовать для получения ее названия с помощью метода database.getCountriesById.
        public let id: Int64?
        
        /// Название страны.
        public let title: String?
        
        public init(id: Int64? = nil, title: String? = nil) {
            self.id = id
            self.title = title
        }
    }
    
    public let country: Country?
    
    /// Возвращает данные о точках, по которым вырезаны профильная и миниатюрная фотографии пользователя, при наличии.
    public final class CropPhoto: Codable {
        
        /// Объект photo фотографии пользователя, из которой вырезается главное фото профиля.
        public let photo: VkPhoto?
        
        /// Вырезанная фотография пользователя. Содержит следующие поля: x (number) — координата X левого верхнего угла в процентах. y (number) — координата Y левого верхнего угла в процентах. x2 (number) — координата X правого нижнего угла в процентах. y2 (number) — координата Y правого нижнего угла в процентах.
        public final class Crop: Codable {
            
            /// Координата X левого верхнего угла в процентах.
            public let x: Int64?
            
            /// Координата Y левого верхнего угла в процентах.
            public let y: Int64?
            
            /// Координата X правого нижнего угла в процентах.
            public let x2: Int64?
            
            /// Координата Y правого нижнего угла в процентах.
            public let y2: Int64?
            
            public init(x: Int64? = nil, y: Int64? = nil, x2: Int64? = nil, y2: Int64? = nil) {
                self.x = x
                self.y = y
                self.x2 = x2
                self.y2 = y2
            }
        }
        
        public let crop: Crop?
        
        /// Миниатюрная квадратная фотография, вырезанная из фотографии crop. Содержит набор полей, аналогичный объекту crop.
        public typealias Rect = Crop
        
        public let rect: Rect?
        
        public init(photo: VkPhoto? = nil, crop: Crop? = nil, rect: Rect? = nil) {
            self.photo = photo
            self.crop = crop
            self.rect = rect
        }
    }
    
    public let cropPhoto: CropPhoto?
    
    /// Короткий адрес страницы. Возвращается строка, содержащая короткий адрес страницы (например, ). Если он не назначен, возвращается +, например, .
    public let domain: String?
    
    /// Информация о высшем учебном заведении пользователя.
    public final class Education: Codable {
        
        /// Идентификатор университета.
        public let university: Int64?
        
        /// Название университета.
        public let universityName: String?
        
        /// Идентификатор факультета.
        public let faculty: Int64?
        
        /// Название факультета.
        public let facultyName: String?
        
        /// Год окончания.
        public let graduation: Int64?
        
        public init(university: Int64? = nil, universityName: String? = nil, faculty: Int64? = nil, facultyName: String? = nil, graduation: Int64? = nil) {
            self.university = university
            self.universityName = universityName
            self.faculty = faculty
            self.facultyName = facultyName
            self.graduation = graduation
        }
    }
    
    public let education: Education?
    
    /// Внешние сервисы, в которые настроен экспорт из ВК ().
    public let exports: String?
    
    /// Имя в заданном падеже.
    public enum FirstName: String, Codable {
        case gen
        case dat
        case nom
        case acc
        case ins
        case abl
    }
    
    public let firstNameCase: FirstName?
    
    /// Количество подписчиков пользователя.
    public let followersCount: Int64?
    
    /// Статус дружбы с пользователем.
    public enum FriendStatus: Int64, Codable {
        case ne_avlaetsa_drugom = 0
        case imeetsa_vhodasaa_zaavka_podpiska_ot_polzovatela = 2
        case otpravlena_zaavka_podpiska_polzovatelu = 1
        case avlaetsa_drugom = 3
    }
    
    public let friendStatus: FriendStatus?
    
    /// Содержимое поля «Любимые игры» из профиля.
    public let games: String?
    
    /// Информация о том, известен ли номер мобильного телефона пользователя. Возвращаемые значения: — известен, — не известен.
    public let hasMobile: VkFlag?
    
    /// , если пользователь установил фотографию для профиля.
    public let hasPhoto: VkFlag?
    
    /// Название родного города.
    public let homeTown: String?
    
    /// Содержимое поля «Интересы» из профиля.
    public let interests: String?
    
    /// Информация о том, есть ли пользователь в закладках у текущего пользователя.
    public let isFavorite: VkFlag?
    
    /// Информация о том, является ли пользователь другом текущего пользователя.
    public let isFriend: VkFlag?
    
    /// Информация о том, скрыт ли пользователь из ленты новостей текущего пользователя.
    public let isHiddenFromFeed: VkFlag?
    
    /// Фамилия в заданном падеже.
    public enum LastName: String, Codable {
        case nom
        case ins
        case gen
        case abl
        case dat
        case acc
    }
    
    public let lastNameCase: LastName?
    
    /// Время последнего посещения.
    public final class LastSeen: Codable {
        
        /// Время последнего посещения в формате Unixtime.
        public let time: UInt64?
        
        /// Тип платформы. Возможные значения: 1 — мобильная версия. 2 — приложение для iPhone. 3 — приложение для iPad. 4 — приложение для Android. 5 — приложение для Windows Phone. 6 — приложение для Windows 10. 7 — полная версия сайта.
        public enum Platform: Int64, Codable {
            case prilozenie_dla_iphone = 2
            case prilozenie_dla_ipad = 3
            case prilozenie_dla_windows_10 = 6
            case prilozenie_dla_android = 4
            case mobilnaa_versia = 1
            case polnaa_versia_sajta = 7
            case prilozenie_dla_windows_phone = 5
        }
        
        public let platform: Platform?
        
        public init(time: UInt64? = nil, platform: Platform? = nil) {
            self.time = time
            self.platform = platform
        }
    }
    
    public let lastSeen: LastSeen?
    
    /// Разделенные запятой идентификаторы списков друзей, в которых состоит пользователь. Поле доступно только для метода .
    public let lists: String?
    
    /// Девичья фамилия.
    public let maidenName: String?
    
    /// Информация о военной службе пользователя.
    public final class Military: Codable {
        
        /// Номер части.
        public let unit: String?
        
        /// Идентификатор части в базе данных.
        public let unitId: Int64?
        
        /// Идентификатор страны, в которой находится часть.
        public let countryId: Int64?
        
        /// Год начала службы.
        public let from: Int64?
        
        /// Год окончания службы.
        public let until: Int64?
        
        public init(unit: String? = nil, unitId: Int64? = nil, countryId: Int64? = nil, from: Int64? = nil, until: Int64? = nil) {
            self.unit = unit
            self.unitId = unitId
            self.countryId = countryId
            self.from = from
            self.until = until
        }
    }
    
    public let military: Military?
    
    /// Содержимое поля «Любимые фильмы» из профиля пользователя.
    public let movies: String?
    
    /// Содержимое поля «Любимая музыка» из профиля пользователя.
    public let music: String?
    
    /// Никнейм (отчество) пользователя.
    public let nickname: String?
    
    /// Информация о текущем роде занятия пользователя.
    public final class Occupation: Codable {
        
        /// Тип. Возможные значения: work — работа. school — среднее образование. university — высшее образование.
        public enum `Type`: String, Codable {
            case school
            case work
            case university
        }
        
        public let `type`: Type?
        
        /// Идентификатор школы, вуза, сообщества компании (в которой пользователь работает).
        public let id: Int64?
        
        /// Название школы, вуза или места работы.
        public let name: String?
        
        public init(type: Type? = nil, id: Int64? = nil, name: String? = nil) {
            self.type = `type`
            self.id = id
            self.name = name
        }
    }
    
    public let occupation: Occupation?
    
    /// Информация о том, находится ли пользователь сейчас на сайте. Если пользователь использует мобильное приложение либо мобильную версию, возвращается дополнительное поле , содержащее . При этом, если используется именно приложение, дополнительно возвращается поле , содержащее его идентификатор.
    public let online: VkFlag?
    
    /// Информация о полях из раздела «Жизненная позиция».
    public final class Personal: Codable {
        
        /// Политические предпочтения. Возможные значения: 1 — коммунистические. 2 — социалистические. 3 — умеренные. 4 — либеральные. 5 — консервативные. 6 — монархические. 7 — ультраконсервативные. 8 — индифферентные. 9 — либертарианские.
        public enum Political: Int64, Codable {
            case libertarianskie = 9
            case socialisticeskie = 2
            case monarhiceskie = 6
            case konservativnye = 5
            case liberalnye = 4
            case kommunisticeskie = 1
            case umerennye = 3
            case indifferentnye = 8
            case ultrakonservativnye = 7
        }
        
        public let political: Political?
        
        /// Языки.
        public let langs: [String]?
        
        /// Мировоззрение.
        public let religion: String?
        
        /// Источники вдохновения.
        public let inspiredBy: String?
        
        /// Главное в людях. Возможные значения: 1 — ум и креативность. 2 — доброта и честность. 3 — красота и здоровье. 4 — власть и богатство. 5 — смелость и упорство. 6 — юмор и жизнелюбие.
        public enum PeopleMain: Int64, Codable {
            case smelost_i_uporstvo = 5
            case umor_i_ziznelubie = 6
            case dobrota_i_cestnost = 2
            case krasota_i_zdorove = 3
            case um_i_kreativnost = 1
            case vlast_i_bogatstvo = 4
        }
        
        public let peopleMain: PeopleMain?
        
        /// Главное в жизни. Возможные значения: 1 — семья и дети. 2 — карьера и деньги. 3 — развлечения и отдых. 4 — наука и исследования. 5 — совершенствование мира. 6 — саморазвитие. 7 — красота и искусство. 8 — слава и влияние.
        public enum LifeMain: Int64, Codable {
            case soversenstvovanie_mira = 5
            case karera_i_dengi = 2
            case krasota_i_iskusstvo = 7
            case slava_i_vlianie = 8
            case razvlecenia_i_otdyh = 3
            case sema_i_deti = 1
            case nauka_i_issledovania = 4
            case samorazvitie = 6
        }
        
        public let lifeMain: LifeMain?
        
        /// Отношение к курению. Возможные значения: 1 — резко негативное. 2 — негативное. 3 — компромиссное. 4 — нейтральное. 5 — положительное.
        public enum Smoking: Int64, Codable {
            case polozitelnoe = 5
            case kompromissnoe = 3
            case nejtralnoe = 4
            case rezko_negativnoe = 1
            case negativnoe = 2
        }
        
        public let smoking: Smoking?
        
        /// Отношение к алкоголю. Возможные значения: 1 — резко негативное. 2 — негативное. 3 — компромиссное. 4 — нейтральное. 5 — положительное.
        public enum Alcohol: Int64, Codable {
            case nejtralnoe = 4
            case polozitelnoe = 5
            case negativnoe = 2
            case rezko_negativnoe = 1
            case kompromissnoe = 3
        }
        
        public let alcohol: Alcohol?
        
        public init(political: Political? = nil, langs: [String]? = nil, religion: String? = nil, inspiredBy: String? = nil, peopleMain: PeopleMain? = nil, lifeMain: LifeMain? = nil, smoking: Smoking? = nil, alcohol: Alcohol? = nil) {
            self.political = political
            self.langs = langs
            self.religion = religion
            self.inspiredBy = inspiredBy
            self.peopleMain = peopleMain
            self.lifeMain = lifeMain
            self.smoking = smoking
            self.alcohol = alcohol
        }
    }
    
    public let personal: Personal?
    
    /// Url фотографии пользователя, имеющей ширину 50 пикселей. В случае отсутствия у пользователя фотографии возвращается .
    public let photo50: String?
    
    /// Url фотографии пользователя, имеющей ширину 100 пикселей. В случае отсутствия у пользователя фотографии возвращается .
    public let photo100: String?
    
    /// Url фотографии пользователя, имеющей ширину 200 пикселей. В случае отсутствия у пользователя фотографии возвращается .
    public let photo200Orig: String?
    
    /// Url фотографии, имеющей ширину 200 пикселей.
    public let photo200: String?
    
    /// Url фотографии, имеющей ширину 400 пикселей. Если у пользователя отсутствует фотография такого размера, в ответе вернется .
    public let photo400Orig: String?
    
    /// Строковый идентификатор главной фотографии профиля пользователя в формате {user_id}_{photo_id}, например, . Обратите внимание, это поле может отсутствовать в ответе.
    public let photoId: String?
    
    /// Url фотографии с максимальной шириной. Может быть возвращена фотография, имеющая ширину как 200, так и 100 пикселей. В случае отсутствия у пользователя фотографии возвращается .
    public let photoMax: String?
    
    /// Url фотографии максимального размера. Может быть возвращена фотография, имеющая ширину как 400, так и 200 пикселей. В случае отсутствия у пользователя фотографии возвращается .
    public let photoMaxOrig: String?
    
    /// Любимые цитаты.
    public let quotes: String?
    
    /// Список родственников.
    public final class Relatives: Codable {
        
        /// Идентификатор пользователя.
        public let id: Int64?
        
        /// Имя родственника (если родственник не является пользователем ВКонтакте, то предыдущее значение id возвращено не будет).
        public let name: String?
        
        /// Тип родственной связи. Возможные значения: child — сын/дочь. sibling — брат/сестра. parent — отец/мать. grandparent — дедушка/бабушка. grandchild — внук/внучка.
        public enum `Type`: String, Codable {
            case parent
            case sibling
            case grandparent
            case child
            case grandchild
        }
        
        public let `type`: Type?
        
        public init(id: Int64? = nil, name: String? = nil, type: Type? = nil) {
            self.id = id
            self.name = name
            self.type = `type`
        }
    }
    
    public let relatives: [Relatives]?
    
    /// Семейное положение.
    public enum Relation: Int64, Codable {
        case ne_ukazano = 0
        case est_drug_est_podruga = 2
        case pomolvlen_pomolvlena = 3
        case vse_slozno = 5
        case v_aktivnom_poiske = 6
        case zenat_zamuzem = 4
        case v_grazdanskom_brake = 8
        case ne_zenat_ne_zamuzem = 1
        case vlublen_vlublena = 7
    }
    
    public let relation: Relation?
    
    /// Список школ, в которых учился пользователь. Массив объектов, описывающих школы.
    public final class Schools: Codable {
        
        /// Идентификатор школы.
        public let id: Int64?
        
        /// Идентификатор страны, в которой расположена школа.
        public let country: Int64?
        
        /// Идентификатор города, в котором расположена школа.
        public let city: Int64?
        
        /// Наименование школы
        public let name: String?
        
        /// Год начала обучения.
        public let yearFrom: Int64?
        
        /// Год окончания обучения.
        public let yearTo: Int64?
        
        /// Год выпуска.
        public let yearGraduated: Int64?
        
        /// Буква класса.
        public let `class`: String?
        
        /// Специализация.
        public let speciality: String?
        
        /// Идентификатор типа.
        public let `type`: Int64?
        
        /// Название типа. Возможные значения для пар type-typeStr: 0 — "школа". 1 — "гимназия". 2 —"лицей". 3 — "школа-интернат". 4 — "школа вечерняя". 5 — "школа музыкальная". 6 — "школа спортивная". 7 — "школа художественная". 8 — "колледж". 9 — "профессиональный лицей". 10 — "техникум". 11 — "ПТУ". 12 — "училище". 13 — "школа искусств".
        public enum TypeStr: String, Codable {
            case skola_iskusstv = "13"
            case ucilise = "12"
            case skola_muzykalnaa = "5"
            case tehnikum = "10"
            case skola = "0"
            case skola_hudozestvennaa = "7"
            case gimnazia = "1"
            case professionalnyj_licej = "9"
            case skolainternat = "3"
            case skola_vecernaa = "4"
            case ptu = "11"
            case skola_sportivnaa = "6"
            case licej = "2"
            case kolledz = "8"
        }
        
        public let typeStr: TypeStr?
        
        public init(id: Int64? = nil, country: Int64? = nil, city: Int64? = nil, name: String? = nil, yearFrom: Int64? = nil, yearTo: Int64? = nil, yearGraduated: Int64? = nil, class: String? = nil, speciality: String? = nil, type: Int64? = nil, typeStr: TypeStr? = nil) {
            self.id = id
            self.country = country
            self.city = city
            self.name = name
            self.yearFrom = yearFrom
            self.yearTo = yearTo
            self.yearGraduated = yearGraduated
            self.class = `class`
            self.speciality = speciality
            self.type = `type`
            self.typeStr = typeStr
        }
    }
    
    public let schools: [Schools]?
    
    /// Короткое имя страницы.
    public let screenName: String?
    
    /// Пол.
    public enum Sex: Int64, Codable {
        case zenskij = 1
        case muzskoj = 2
        case pol_ne_ukazan = 0
    }
    
    public let sex: Sex?
    
    /// Адрес сайта, указанный в профиле.
    public let site: String?
    
    /// Статус пользователя. Возвращается строка, содержащая текст статуса, расположенного в профиле под именем. Если включена опция «Транслировать в статус играющую музыку», возвращается дополнительное поле , содержащее информацию о композиции.
    public let status: String?
    
    /// Временная зона. Только при запросе информации о текущем пользователе.
    public let timezone: Int64?
    
    /// Информация о том, есть ли на странице пользователя «огонёк».
    public let trending: VkFlag?
    
    /// Любимые телешоу.
    public let tv: String?
    
    /// Список вузов, в которых учился пользователь. Массив объектов, описывающих университеты.
    public final class Universities: Codable {
        
        /// Идентификатор университета.
        public let id: Int64?
        
        /// Идентификатор страны, в которой расположен университет.
        public let country: Int64?
        
        /// Идентификатор города, в котором расположен университет.
        public let city: Int64?
        
        /// Наименование университета.
        public let name: String?
        
        /// Идентификатор факультета.
        public let faculty: Int64?
        
        /// Наименование факультета.
        public let facultyName: String?
        
        /// Идентификатор кафедры.
        public let chair: Int64?
        
        /// Наименование кафедры.
        public let chairName: String?
        
        /// Год окончания обучения.
        public let graduation: Int64?
        
        /// Форма обучения.
        public let educationForm: String?
        
        /// Статус (например, «Выпускник (специалист)»).
        public let educationStatus: String?
        
        public init(id: Int64? = nil, country: Int64? = nil, city: Int64? = nil, name: String? = nil, faculty: Int64? = nil, facultyName: String? = nil, chair: Int64? = nil, chairName: String? = nil, graduation: Int64? = nil, educationForm: String? = nil, educationStatus: String? = nil) {
            self.id = id
            self.country = country
            self.city = city
            self.name = name
            self.faculty = faculty
            self.facultyName = facultyName
            self.chair = chair
            self.chairName = chairName
            self.graduation = graduation
            self.educationForm = educationForm
            self.educationStatus = educationStatus
        }
    }
    
    public let universities: [Universities]?
    
    /// Возвращается , если страница пользователя верифицирована, — если нет.
    public let verified: VkFlag?
    
    /// Режим стены по умолчанию. Возможные значения: , .
    public enum WallDefault: String, Codable {
        case all
        case owner
    }
    
    public let wallDefault: WallDefault?
    
    public init(id: Int64, firstName: String, lastName: String, deactivated: String, isClosed: Bool, canAccessClosed: Bool, about: String? = nil, activities: String? = nil, bdate: String? = nil, blacklisted: VkFlag? = nil, blacklistedByMe: VkFlag? = nil, books: String? = nil, canPost: VkFlag? = nil, canSeeAllPosts: VkFlag? = nil, canSeeAudio: VkFlag? = nil, canSendFriendRequest: VkFlag? = nil, canWritePrivateMessage: VkFlag? = nil, career: Career? = nil, city: City? = nil, commonCount: Int64? = nil, connections: [String: String]? = nil, contacts: Contacts? = nil, counters: Counters? = nil, country: Country? = nil, cropPhoto: CropPhoto? = nil, domain: String? = nil, education: Education? = nil, exports: String? = nil, firstNameCase: FirstName? = nil, followersCount: Int64? = nil, friendStatus: FriendStatus? = nil, games: String? = nil, hasMobile: VkFlag? = nil, hasPhoto: VkFlag? = nil, homeTown: String? = nil, interests: String? = nil, isFavorite: VkFlag? = nil, isFriend: VkFlag? = nil, isHiddenFromFeed: VkFlag? = nil, lastNameCase: LastName? = nil, lastSeen: LastSeen? = nil, lists: String? = nil, maidenName: String? = nil, military: Military? = nil, movies: String? = nil, music: String? = nil, nickname: String? = nil, occupation: Occupation? = nil, online: VkFlag? = nil, personal: Personal? = nil, photo50: String? = nil, photo100: String? = nil, photo200Orig: String? = nil, photo200: String? = nil, photo400Orig: String? = nil, photoId: String? = nil, photoMax: String? = nil, photoMaxOrig: String? = nil, quotes: String? = nil, relatives: [Relatives]? = nil, relation: Relation? = nil, schools: [Schools]? = nil, screenName: String? = nil, sex: Sex? = nil, site: String? = nil, status: String? = nil, timezone: Int64? = nil, trending: VkFlag? = nil, tv: String? = nil, universities: [Universities]? = nil, verified: VkFlag? = nil, wallDefault: WallDefault? = nil) {
        self.id = id
        self.firstName = firstName
        self.lastName = lastName
        self.deactivated = deactivated
        self.isClosed = isClosed
        self.canAccessClosed = canAccessClosed
        self.about = about
        self.activities = activities
        self.bdate = bdate
        self.blacklisted = blacklisted
        self.blacklistedByMe = blacklistedByMe
        self.books = books
        self.canPost = canPost
        self.canSeeAllPosts = canSeeAllPosts
        self.canSeeAudio = canSeeAudio
        self.canSendFriendRequest = canSendFriendRequest
        self.canWritePrivateMessage = canWritePrivateMessage
        self.career = career
        self.city = city
        self.commonCount = commonCount
        self.connections = connections
        self.contacts = contacts
        self.counters = counters
        self.country = country
        self.cropPhoto = cropPhoto
        self.domain = domain
        self.education = education
        self.exports = exports
        self.firstNameCase = firstNameCase
        self.followersCount = followersCount
        self.friendStatus = friendStatus
        self.games = games
        self.hasMobile = hasMobile
        self.hasPhoto = hasPhoto
        self.homeTown = homeTown
        self.interests = interests
        self.isFavorite = isFavorite
        self.isFriend = isFriend
        self.isHiddenFromFeed = isHiddenFromFeed
        self.lastNameCase = lastNameCase
        self.lastSeen = lastSeen
        self.lists = lists
        self.maidenName = maidenName
        self.military = military
        self.movies = movies
        self.music = music
        self.nickname = nickname
        self.occupation = occupation
        self.online = online
        self.personal = personal
        self.photo50 = photo50
        self.photo100 = photo100
        self.photo200Orig = photo200Orig
        self.photo200 = photo200
        self.photo400Orig = photo400Orig
        self.photoId = photoId
        self.photoMax = photoMax
        self.photoMaxOrig = photoMaxOrig
        self.quotes = quotes
        self.relatives = relatives
        self.relation = relation
        self.schools = schools
        self.screenName = screenName
        self.sex = sex
        self.site = site
        self.status = status
        self.timezone = timezone
        self.trending = trending
        self.tv = tv
        self.universities = universities
        self.verified = verified
        self.wallDefault = wallDefault
    }

}