# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2.1
jobs:
  build:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
