//
//  SwiftFile.swift
//  
//
//  Created by Nickolay Truhin on 28.11.2020.
//

import Foundation

protocol SwiftFile {
    var params: [RespParameter] { get }
    var description: String { get }
    var string: String { get }
}

extension SwiftFile {
    var wrappedString: String {
        """
        // Vkontakter - VK Bot Swift SDK.
        // This file is autogenerated by API package.

        \(string)
        """
    }
    
}

struct TypeFile: SwiftFile {
    let description: String
    let params: [RespParameter]
    let apiName: String
    
    var codeName: String {
        apiName.camelized.capitalizingFirstLetter()
    }
    
    var string: String {
        """
        /**
         \(description)

         SeeAlso VK API Reference:
         [\(codeName)](https://vk.com/dev/objects/\(apiName)
         */
        public final class \(codeName): Codable {
            \(params.generate.i(1))
            \(params.generateInit)
        }
        """
    }
}

struct MethodExtensionFile: SwiftFile {
    let description: String
    let params: [RespParameter]
    let methodGroup: String
    let method: Method
    let respParams: [RespParameter] // if empty then Flag

    var methodCodeCapitalized: String {
        method.codeName.capitalizingFirstLetter()
    }
    
    var methodApi: String {
        methodGroup + "." + method.apiName
    }
    
    var respType: String {
        respParams.isEmpty ? "VkFlag" : methodCodeCapitalized.capitalizingFirstLetter() + "Resp"
    }
    
    var respTypeContent: String {
        respParams.isEmpty ? "" : "\nfinal class \(respType): Codable {\n\("\n".i(1))\((respParams.generate + "\n").i(1))\(respParams.generateInit)\n}\n".i(1)
    }
    
    var paramsType: String {
        methodCodeCapitalized.capitalizingFirstLetter() + "Params"
    }

    var string: String {
        """
        public extension Bot {

            /// Parameters container struct for `\(method.codeName)` method
            final class \(paramsType): JSONEncodable {

                \(params.generate.i(2))
                \(params.generateInit.i(1))
            }
            \(respTypeContent)
            /**
             \(description)

             See also VK API Reference:
             [\(methodCodeCapitalized)](https://vk.com/dev/\(methodApi))
             
             - Parameters:
                 - params: Parameters container, see `\(paramsType)` struct
             - Throws: Throws on errors
             - Returns: Future of `\(respType)` type
             */
            @discardableResult
            func \(method.codeName)(params: \(paramsType)) throws -> Future<\(respType)> {
                let headers = httpHeaders(for: params)
                return try client
                    .request(endpoint: "\(methodApi)", params: params, headers: headers)
                    .flatMapThrowing { (container) -> \(respType) in
                        return try self.processContainer(container)
                }
            }
        }
        """
    }
}

extension String {
    var safeNamed: String {
        [ "class", "enum", "type" ].contains { caseInsensitiveCompare($0) == .orderedSame } ?  "`\(self)`" : self
    }
}

extension RespParameter {
    var generate: String {
        var str = [String]()
        if let desc = description, !desc.isEmpty {
            str.append("/// \(desc)\n")
        }
        
        let varPart = "let \(name.safeNamed): \(typeString)"

        str.append("public ")
        switch type {
        case _ where ParamType.typedCases.contains(type), .Array: break
        case let .Enum(data):
            guard let data = data else { fatalError() }
            let casesContent: String = data.cases.map {
                let valueStr: String
                switch data.casesType {
                case .String:
                    valueStr = "\"\($0.value)\""
                default:
                    valueStr = String(describing: $0.value)
                }
                return "\ncase \($0.key != $0.value as? String ? $0.key + " = " + valueStr : $0.key)".i(1)
            }.joined()
            let name = data.name.safeNamed
            str.append("enum \(name): \(data.casesType.string!), Codable {\(casesContent)\n}\n\n")
        case let .Typealias(data):
            guard let data = data else { fatalError() }
            str.append("typealias \(name.capitalizingFirstLetter()) = \(data)\n\n")
        case let .Object(data):
            guard let data = data else { fatalError() }
            let initStr = data.params.generateInit
            str.append("final class \(data.name): Codable {\n\n\(data.params.generate)".i(1) + "\n".i(1) + "\(initStr)}\n\n")
        default:
            fatalError()
        }
        
        str.append(varPart)
        str.append("\n")
        return str.joined()
    }
}

extension Array where Element == RespParameter {

    var generate: String {
        map { $0.generate }.joined(separator: "\n")
    }
    
    var generateInit: String {
        let initContent = map { param in "\nself.\(param.name) = \(param.name.safeNamed)" }.joined().i(1)
        let initParams = map { param in "\(param.name): \(param.typeString)\(param.required ? "" : " = nil")" }.joined(separator: ", ")
        return "public init(\(initParams)) {\(initContent)\n".i(1) + "}\n"
    }

}
