// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

public extension Bot {

    /// Parameters container struct for `addCallbackServer` method
    struct AddCallbackServerParams: JSONEncodable {

        /// Идентификатор сообщества.
        public let groupId: UInt64
        
        /// URL сервера.
        public let url: String
        
        /// Название сервера.
        public let title: String
        
        /// Секретный ключ.
        public let secretKey: String?
        
        public init(groupId: UInt64, url: String, title: String, secretKey: String? = nil) {
            self.groupId = groupId
            self.url = url
            self.title = title
            self.secretKey = secretKey
        }
    
    }
    
    struct AddCallbackServerResp: Codable {
    
        public let serverId: UInt64
        
        public init(serverId: UInt64) {
            self.serverId = serverId
        }
    
    }
    
    /**
     Добавляет сервер для Callback API в сообщество.
     После успешного выполнения возвращает идентификатор добавленного сервера в поле server_id (integer).

     See also VK API Reference:
     [AddCallbackServer](https://vk.com/dev/groups.addCallbackServer)
     
     - Parameters:
         - params: Parameters container, see `AddCallbackServerParams` struct
     - Throws: Throws on errors
     - Returns: Future of `AddCallbackServerResp` type
     */
    @discardableResult
    func addCallbackServer(params: AddCallbackServerParams) throws -> Future<AddCallbackServerResp> {
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "groups.addCallbackServer", params: params, headers: headers)
            .flatMapThrowing { (container) -> AddCallbackServerResp in
                return try self.processContainer(container)
        }
    }
}