// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

public extension Bot {

    /// Parameters container struct for `getCallbackServers` method
    struct GetCallbackServersParams: JSONEncodable {
        
        /// Идентификатор сообщества.
        let groupId: UInt64
        
        /// Идентификаторы серверов, данные о которых нужно получить. По умолчанию возвращаются все серверы.
        let serverIds: [UInt64]?
        
        
        public init(groupId: UInt64, serverIds: [UInt64]? = nil) {
            self.groupId = groupId
            self.serverIds = serverIds
        }
    }
    
    struct GetCallbackServersResp: Codable {
    
        /// Идентификатор сервера.
        let id: String?
        
        /// Название сервера.
        let title: String?
        
        /// Идентификатор пользователя, который добавил сервер (может содержать 0).
        let creatorId: String?
        
        /// URL сервера.
        let url: String?
        
        /// Секретный ключ.
        let secretKey: String?
        
        /// Статус сервера. Возможные значения: unconfigured — адрес не задан. failed — подтвердить адрес не удалось. wait — адрес ожидает подтверждения. ok — сервер подключен.
        let status: String?
        
        
    }
    
    /**
     Получает информацию о серверах для в сообществе.
     Возвращает число серверов в поле count (integer) и массив объектов items с данными о серверах.

     See also VK API Reference:
     [GetCallbackServers](https://vk.com/dev/groups.getCallbackServers)
     
     - Parameters:
         - params: Parameters container, see `GetCallbackServersParams` struct
     - Throws: Throws on errors
     - Returns: Future of `GetCallbackServersResp` type
     */
    @discardableResult
    func getCallbackServers(params: GetCallbackServersParams) throws -> Future<GetCallbackServersResp> {
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "groups.getCallbackServers", params: params, headers: headers)
            .flatMapThrowing { (container) -> GetCallbackServersResp in
                return try self.processContainer(container)
        }
    }
}
