// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

public extension Bot {

    /// Parameters container struct for `getCallbackConfirmationCode` method
    struct GetCallbackConfirmationCodeParams: JSONEncodable {
        
        /// Идентификатор сообщества.
        let groupId: UInt64
        
        
        public init(groupId: UInt64) {
            self.groupId = groupId
        }
    }
    
    /**
     Позволяет получить строку, необходимую для подтверждения адреса сервера в .
     Возвращает строку, которую необходимо использовать в качестве ответа на уведомление с типом "confirmation" для подтверждения адреса сервера в Callback API.

     See also VK API Reference:
     [GetCallbackConfirmationCode](https://vk.com/dev/groups.getCallbackConfirmationCode)
     
     - Parameters:
         - params: Parameters container, see `GetCallbackConfirmationCodeParams` struct
     - Throws: Throws on errors
     - Returns: Future of `VkFlag` type
     */
    @discardableResult
    func getCallbackConfirmationCode(params: GetCallbackConfirmationCodeParams) throws -> Future<VkFlag> {
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "groups.getCallbackConfirmationCode", params: params, headers: headers)
            .flatMapThrowing { (container) -> VkFlag in
                return try self.processContainer(container)
        }
    }
}
