// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

public extension Bot {

    /// Parameters container struct for `saveMessagesPhoto` method
    class SaveMessagesPhotoParams: JSONEncodable {

        /// Параметр, возвращаемый в результате загрузки фотографии на сервер.
        public let photo: String
        
        /// Параметр, возвращаемый в результате загрузки фотографии на сервер.
        public let server: Int64?
        
        /// Параметр, возвращаемый в результате загрузки фотографии на сервер.
        public let hash: String?
        
        public init(photo: String, server: Int64? = nil, hash: String? = nil) {
            self.photo = photo
            self.server = server
            self.hash = hash
        }
    
    }
    
    struct Photo: Codable {
    
        public let id: Int64?
        
        public let pid: Int64?
        
        public let aid: Int64?
        
        public let ownerId: Int64?
        
        public let src: String?
        
        public let srcBig: String?
        
        public let srcSmall: String?
        
        public let created: String?
        
        public let srcXbig: String?
        
        public let srcXxbig: String?
        
        public init(id: Int64? = nil, pid: Int64? = nil, aid: Int64? = nil, ownerId: Int64? = nil, src: String? = nil, srcBig: String? = nil, srcSmall: String? = nil, created: String? = nil, srcXbig: String? = nil, srcXxbig: String? = nil) {
            self.id = id
            self.pid = pid
            self.aid = aid
            self.ownerId = ownerId
            self.src = src
            self.srcBig = srcBig
            self.srcSmall = srcSmall
            self.created = created
            self.srcXbig = srcXbig
            self.srcXxbig = srcXxbig
        }
    
    }
    
    /**
     Сохраняет фотографию после успешной загрузки на URI, полученный методом photos.getMessagesUploadServer.
     После успешного выполнения возвращает массив с загруженной фотографией, возвращённый объект имеет поля id, pid, aid, owner_id, src, src_big, src_small, created.

     See also VK API Reference:
     [SaveMessagesPhoto](https://vk.com/dev/photos.saveMessagesPhoto)
     
     - Parameters:
         - params: Parameters container, see `SaveMessagesPhotoParams` struct
     - Throws: Throws on errors
     - Returns: Future of `[Photo]` type
     */
    @discardableResult
    func saveMessagesPhoto(params: SaveMessagesPhotoParams) throws -> Future<[Photo]> {
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "photos.saveMessagesPhoto", params: params, headers: headers)
            .flatMapThrowing { (container) -> [Photo] in
                return try self.processContainer(container)
        }
    }
}