// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

public extension Bot {

    /// Parameters container struct for `addCallbackServer` method
    struct AddCallbackServerParams: JSONEncodable {
        
        /// Идентификатор сообщества.
        let groupId: UInt64
        
        /// URL сервера.
        let url: String
        
        /// Название сервера.
        let title: String
        
        /// Секретный ключ.
        let secretKey: String?
        
        
        public init(groupId: UInt64, url: String, title: String, secretKey: String? = nil) {
            self.groupId = groupId
            self.url = url
            self.title = title
            self.secretKey = secretKey
        }
    }
    
    /**
     Добавляет сервер для в сообщество.
     После успешного выполнения возвращает идентификатор добавленного сервера в поле server_id (integer).

     See also VK API Reference:
     [AddCallbackServer](https://vk.com/dev/groups.addCallbackServer)
     
     - Parameters:
         - params: Parameters container, see `AddCallbackServerParams` struct
     - Throws: Throws on errors
     - Returns: Future of `VkFlag` type
     */
    @discardableResult
    func addCallbackServer(params: AddCallbackServerParams) throws -> Future<VkFlag> {
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "groups.addCallbackServer", params: params, headers: headers)
            .flatMapThrowing { (container) -> VkFlag in
                return try self.processContainer(container)
        }
    }
}
