// Vkontakter - VK Bot Swift SDK.
// This file is autogenerated by API package.

import AnyCodable

public extension Bot {

    /// Parameters container struct for `getCallbackConfirmationCode` method
    struct GetCallbackConfirmationCodeParams: JSONEncodable {

        /// Идентификатор сообщества.
        public let groupId: UInt64
        
        public init(groupId: UInt64) {
            self.groupId = groupId
        }
    
    }
    
    final struct GetCallbackConfirmationCodeResp: Codable {
    
        public let code: String
        
        public init(code: String) {
            self.code = code
        }
    
    }
    
    /**
     Позволяет получить строку, необходимую для подтверждения адреса сервера в Callback API.
     Возвращает строку, которую необходимо использовать в качестве ответа на уведомление с типом "confirmation" для подтверждения адреса сервера в Callback API.

     See also VK API Reference:
     [GetCallbackConfirmationCode](https://vk.com/dev/groups.getCallbackConfirmationCode)
     
     - Parameters:
         - params: Parameters container, see `GetCallbackConfirmationCodeParams` struct
     - Throws: Throws on errors
     - Returns: Future of `GetCallbackConfirmationCodeResp` type
     */
    @discardableResult
    func getCallbackConfirmationCode(params: GetCallbackConfirmationCodeParams) throws -> Future<GetCallbackConfirmationCodeResp> {
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "groups.getCallbackConfirmationCode", params: params, headers: headers)
            .flatMapThrowing { (container) -> GetCallbackConfirmationCodeResp in
                return try self.processContainer(container)
        }
    }
}